replicaCount: 1

image:
  repository: yuvipanda/kubessh-kubessh
  tag: 01863eb
  pullPolicy: Always

  name: yuvipanda/kubessh-kubessh
service:
  type: LoadBalancer
  port: 22

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  enabled: true
