name: Publish chart
on: [push]

jobs:
  build:
    name: Publish Helm Chart
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --no-cache-dir -r dev-requirements.txt
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Deploy SSH key
        env:
          CHARTPRESS_SSH_KEY: ${{ secrets.CHARTPRESS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${CHARTPRESS_SSH_KEY}" > ~/.ssh/id_rsa
      - name: Publish chart
        run: |
          source venv/bin/activate
          cd helm-chart
          chartpress --push --publish-chart